### ISSUE TITLE
Gem 'jwt' breaks Ruby 1.9.3 support

### ISSUE THREAD

**Issue by kennym** [GetStream/stream-ruby#51]
The latest commits have broken support for Ruby 1.9.3, because the gem `jwt` doesn't support it. See here: https://travis-ci.org/GetStream/stream-ruby/jobs/115152833

```
/home/travis/.rvm/rubies/ruby-1.9.3-p551/bin/ruby -S rspec ./spec/client_spec.rb ./spec/errors_spec.rb ./spec/feed_spec.rb ./spec/integration_spec.rb ./spec/signer_spec.rb ./spec/stream_spec.rb
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/jwt-1.5.3/lib/jwt/decode.rb:2:in `require': /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/jwt-1.5.3/lib/jwt/verify.rb:7: unknown type of %string (SyntaxError)
      %i[verify_aud verify_expiration ...
         ^
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/jwt-1.5.3/lib/jwt/verify.rb:7: syntax error, unexpected $end
      %i[verify_aud verify_expiration ...
         ^
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/jwt-1.5.3/lib/jwt/decode.rb:2:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/jwt-1.5.3/lib/jwt.rb:3:in `require'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/jwt-1.5.3/lib/jwt.rb:3:in `<top (required)>'
```

**Comment by kennym** [comment]
Do your customers rely on Ruby 1.9.3 support? @tbarbugli @tschellenbach
