### ISSUE TITLE
JSON Parse Error

### ISSUE THREAD

**Issue by tommotaylor** [GetStream/stream-ruby#86]
For my `rails-api` Rails App I am getting the following error with both the `stream-ruby` and `stream-rails` gems.

Environment:
- Ruby 2.3.1
- Rails 5.0.0.1

This error occurs whenever trying to create an activity, either as part of creating an ActiveRecord Object when `include StreamRails::Activity` is on the model, or simply creating an activity in the console with:

`response = user_feed.add_activity(data)`

```
JSON::ParserError: 743: unexpected token at ''
	from /Users/tom/.gem/ruby/2.3.1/gems/json-2.0.2/lib/json/common.rb:156:in `parse'
	from /Users/tom/.gem/ruby/2.3.1/gems/json-2.0.2/lib/json/common.rb:156:in `parse'
	from /Users/tom/.gem/ruby/2.3.1/gems/stream-ruby-2.6.0/lib/stream/client.rb:190:in `_build_error_message'
	from /Users/tom/.gem/ruby/2.3.1/gems/stream-ruby-2.6.0/lib/stream/client.rb:177:in `block in call'
	from /Users/tom/.gem/ruby/2.3.1/gems/faraday-0.15.0/lib/faraday/response.rb:61:in `on_complete'
	from /Users/tom/.gem/ruby/2.3.1/gems/stream-ruby-2.6.0/lib/stream/client.rb:166:in `call'
	from /Users/tom/.gem/ruby/2.3.1/gems/faraday-0.15.0/lib/faraday/rack_builder.rb:143:in `build_response'
	from /Users/tom/.gem/ruby/2.3.1/gems/faraday-0.15.0/lib/faraday/connection.rb:387:in `run_request'
	from /Users/tom/.gem/ruby/2.3.1/gems/stream-ruby-2.6.0/lib/stream/client.rb:150:in `make_http_request'
	from /Users/tom/.gem/ruby/2.3.1/gems/stream-ruby-2.6.0/lib/stream/client.rb:115:in `make_request'
	from /Users/tom/.gem/ruby/2.3.1/gems/stream-ruby-2.6.0/lib/stream/feed.rb:67:in `add_activity'
	from (irb):21
	from /Users/tom/.gem/ruby/2.3.1/gems/railties-5.0.0.1/lib/rails/commands/console.rb:65:in `start'
	from /Users/tom/.gem/ruby/2.3.1/gems/railties-5.0.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/tom/.gem/ruby/2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/tom/.gem/ruby/2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
... 6 levels...
	from /Users/tom/.gem/ruby/2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/tom/.gem/ruby/2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/tom/.gem/ruby/2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/tom/.gem/ruby/2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/tom/.gem/ruby/2.3.1/gems/spring-1.7.2/lib/spring/commands/rails.rb:6:in `call'
	from /Users/tom/.gem/ruby/2.3.1/gems/spring-1.7.2/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/tom/.gem/ruby/2.3.1/gems/spring-1.7.2/lib/spring/application.rb:191:in `block in serve'
	from /Users/tom/.gem/ruby/2.3.1/gems/spring-1.7.2/lib/spring/application.rb:161:in `fork'
	from /Users/tom/.gem/ruby/2.3.1/gems/spring-1.7.2/lib/spring/application.rb:161:in `serve'
	from /Users/tom/.gem/ruby/2.3.1/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'
	from /Users/tom/.gem/ruby/2.3.1/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
	from /Users/tom/.gem/ruby/2.3.1/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'
	from /Users/tom/.gem/ruby/2.3.1/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/tom/.rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/tom/.rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by ruggi** [comment]
looks like the client fails at deserializing the (validation?) error, can you attach an example of an activity that causes this? also feel free to reach us out at support@getstream.io

**Comment by tommotaylor** [comment]
I think it is anything that is hitting the server. For instance:

`user_feed_23 = client.feed('user', '23')` returns: `#<Stream::Feed:0x007fe3f2b41238 @id="user:23"...`

But `user_feed_23.followers` will error, as will anything like:
- `user_feed_23.add_activity({actor: "User:24", verb: "write", object: "Note:1", time: Time.zone.now})`
- `user_feed_24.follow("user", "23")`

**Comment by ruggi** [comment]
Looks like it was something broken on our dashboard. If you try now, it should work fine.
Could you send an email to support@getstream.io with your report above ^ so we can investigate further the problem that caused it?
Also, if you can confirm this is solved I'll close the issue. Thanks!

**Comment by tommotaylor** [comment]
@ruggi I've retried, and also created a new "app" in the Stream dashboard without any feed groups, and then with feed groups "user" and "timeline". I still get the same error when attempting to do anything that reaches for the Stream server.

**Comment by ruggi** [comment]
@tommotaylor it was indeed a bug on our dashboard affecting some apps, fixed now.

**Comment by tommotaylor** [comment]
@ruggi amazing, thank you very much for the quick fix!
